padaria/core/urls.py
from django.urls import path
from .views import home, detail, register_customer, register_client, product_list, wish_list

app_name = 'core'

urlpatterns = [
    path('', home, name="home"),
    path('product/list', product_list, name="product_list"),
    path('wish/list', wish_list, name="wish_list" ),
    path('register/client', register_client, name="register_client"),
    path('register/product', register_customer, name="register_product"),
    path('detail/<int:pk>/', detail, name='detail'),
]

padaria/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('padaria.core.urls', namespace='core')),
    path('admin/', admin.site.urls),
]

padaria/core/models.py
from django.db import models
from django.urls import reverse


# Tabela de Clientes
class ClientModel(models.Model):
    first_name = models.CharField("Nome", max_length=80)
    last_name = models.CharField("Sobrenome", max_length=200)
    date_of_birth = models.DateField("Data de nascimento")
    cpf = models.CharField("CPF", max_length=11)
    phone_number = models.CharField("Número de telefone", max_length=11)
    address = models.CharField("Endereço", max_length=254)
    created_at = models.DateTimeField("Criado em",auto_now_add=True)
    updated_at = models.DateTimeField("Atualizado em", auto_now=True)


    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"
        ordering = ['first_name']

    def __str__(self):
        return self.first_name


# Tabela de Produtos
class ProductModel(models.Model):
    image = models.URLField("Imagem")
    name = models.CharField("Nome", max_length=254)
    amount = models.PositiveIntegerField("Quantidade")
    value = models.DecimalField("Valor", max_digits=10, decimal_places=2)
    description = models.TextField("Descrição", blank=True)
    created_at = models.DateTimeField("Criado em",auto_now_add=True)
    updated_at = models.DateTimeField("Atualizado em", auto_now=True)


    class Meta:
        verbose_name = "Produto"
        verbose_name_plural = "Produtos"
        ordering = ['id']


    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('core:detail', kwargs={'pk': self.pk})


# Tabela de Vendas
class SaleModel(models.Model):
    order_number = models.CharField("Número de Pedido", max_length=4)
    amount_buy = models.PositiveIntegerField("Quantidade")
    value_sale = models.DecimalField("Total", max_digits=10, decimal_places=2, null=True, blank=True)
    total = models.DecimalField("Total", max_digits=10, decimal_places=2, null=True, blank=True)
    client = models.ForeignKey(ClientModel, 
                               verbose_name="Cliente", 
                               on_delete=models.CASCADE, 
                               related_name="ordereds", 
                             
                               )
    product = models.ForeignKey(ProductModel, 
                                verbose_name="Produto", 
                                on_delete=models.CASCADE, 
                                related_name="ordereds", 
                                null=True, 
                                blank=True)
    sale_created_at = models.DateTimeField("Vendido em",auto_now_add=True)

    class Meta:
        verbose_name = "Venda"
        verbose_name_plural = "Vendas"
        ordering = ['order_number']

    def __str__(self):
        return "Número de pedido: " + self.order_number
    
    

padaria/core/forms.py
from django.forms import ModelForm
from django import forms
from .models import ProductModel, SaleModel, ClientModel

class ProductForm(ModelForm):
    class Meta:
        model = ProductModel
        fields = ["image","name", "amount", "value", "description"]

        widgets = {
            "image": forms.TextInput(attrs={"class":"form-control border border-dark", "placeholder":"URL da Imagem"}),
            "name": forms.TextInput(attrs={"class":"form-control border border-dark", "placeholder":"Nome do produto"}),
            "amount": forms.NumberInput(attrs={"class":"form-control border border-dark", "placeholder":"Quantidade"}),
            "value": forms.TextInput(attrs={"class":"form-control border border-dark", "placeholder":"Valor unitário R$"}),
            "description": forms.Textarea(attrs={"class":"form-control border border-dark", "placeholder":"Descrição"}),
        } 
        

class ClientForm(ModelForm):
    class Meta:
        model = ClientModel
        fields = ["first_name","last_name","date_of_birth","cpf","phone_number", "address" ] 


        widgets = {
            "first_name": forms.TextInput(attrs={"class":"form-control border border-dark", "placeholder":"Nome"}),
            "last_name": forms.TextInput(attrs={"class":"form-control border border-dark", "placeholder":"Sobrenome"}),
            "date_of_birth": forms.DateInput(attrs={"class":"form-control border border-dark", "placeholder":"Data de nascimento"}),
            "cpf": forms.TextInput(attrs={"class":"form-control border border-dark", "placeholder":"Cpf"}),
            "phone_number": forms.TextInput(attrs={"class":"form-control border border-dark", "placeholder":"Telefone"}),
            "address": forms.Textarea(attrs={"class":"form-control border border-dark", "placeholder":"Endereço"}),
        } 

class SaleForm(ModelForm):
    class Meta:
        model = SaleModel
        fields = ["order_number","amount_buy", "client", "product"] 

        widgets = {
            
            "client": forms.Select(attrs={"class":"form-select border border-dark", "placeholder":"Nome do produto"}),
            "amount_buy": forms.NumberInput(attrs={"class":"form-control border border-dark", "placeholder":"Quantidade"}),
        } 

padaria/core/views.py
from django.shortcuts import render
from .models import ProductModel, SaleModel, ClientModel
from .forms import ProductForm, ClientForm, SaleForm
from django.contrib import messages

def home(request):
    obj = ProductModel.objects.all()
    
    return render(request, 'home.html', {'products': obj})


def product_list(request):
    obj = ProductModel.objects.all()
    return render(request, 'product_list.html', {'products': obj})


def detail(request, pk):
    obj = ProductModel.objects.get(pk=pk)
    sale = SaleForm()
    
    if request.method == "POST":
    
        client = request.POST.get('client')
        amount_buy = request.POST.get('amount_buy')
        if obj.amount > int(amount_buy):
            quantidade = obj.amount - int(amount_buy)
            obj.amount = quantidade
            obj.save()
         
            sale_model = SaleModel()

            sale_model.product_id = pk
            sale_model.client_id = client
            sale_model.amount_buy = amount_buy
            sale_model.order_number = "%04d"% int(obj.pk)
            valor = float(obj.value)
            sale_model.value_sale = valor
            quantidade = int(sale_model.amount_buy)
            sale_model.total = quantidade * valor

            sale_model.save()

            messages.success(request, "Compra realizada com Sucesso!","alert-success")
        else:
            messages.error(request, "Quantidade insuficiênte!",'alert-danger')

    return render(request, "detail.html" ,{'products': obj, 'sale': sale})


def wish_list(request):
    sale = SaleModel.objects.all()
    return render(request, 'wish_list.html', {'sales': sale })          


def register_customer(request):
    form = ProductForm()
    form_product = ProductForm(request.POST)

    if request.method == "POST":
        if form_product.is_valid():
            form_product.save()
            messages.success(request, "Produto cadastrado com sucesso!","alert-success")

        if not form_product.is_valid():
            messages.success(request, "Error no formulário dados inválido!","alert-danger")

    return render(request, 'register_product.html', {"form": form})


def register_client(request):
    form = ClientForm()
    form_client = ClientForm(request.POST)

    if request.method == "POST":
        if form_client.is_valid():
            form_client.save()
    
            messages.success(request, "Cliente cadastrado com sucesso!","alert-success")
        
        if not form_client.is_valid():
            messages.success(request, "Error no formulário dados inválido!","alert-danger")
        
    return render(request, 'register_client.html', {"form": form})

padaria/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Desenvolvimento web com Django Framework para padaria.">
    <meta name="author" content="Geovane Carvalho">
    
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <title>Padaría-delivery</title>
  </head>

  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand m-2 p-2" href="{% url 'core:home' %}">Padaria Delivery</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item btn btn-sm btn-outline-light m-1" href="{% url 'core:home' %}">Home</a>
          <a class="nav-item btn btn-sm btn-outline-light m-1" href="{% url 'core:register_client' %}">Cadastrar Cliente</a>
          <a class="nav-item btn btn-sm btn-outline-light m-1" href="{% url 'core:register_product' %}">Cadastrar Produto</a>
          <a class="nav-item btn btn-sm btn-outline-light m-1" href="{% url 'core:wish_list'%}">Lista de Pedidos</a>
          <a class="nav-item btn btn-sm btn-outline-light m-1" href="{% url 'core:product_list'%}">Estoque de Produtos</a>
        </div>
      </div>
    </nav>
  </header>
    
  <body cz-shortcut-listen="true">
    {% block content %}

    {% endblock content %}

    <footer class="text-muted bg-dark p-4 footer-bottom">
        <h3 class="text-white text-center">FALE CONOSCO</h3>
        <p class="text-white text-center">FONE: (061)3313-1456</p>
        <p class="text-white text-center">EMAIL: padaria_delivery@gmail.com</p>
    </footer>

  
  
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>


    
  </body>
</html>

padaria/core/templates/detail.html
{% extends "base.html" %}

{% block content %}
    <div class="container p-5">
        <div class="row">
            <div class="col">
                
              <h2 class="text-center">{{products.name|upper}}</h2>
              
                <p class="p-3" style="text-align:justify">&emsp;&emsp;&emsp;{{products.description}}</p>
                <table class="table p-5">
                    <thead>
                      <tr class="text-center">
                        <th scope="col">IMAGEM</th>
                        <th scope="col">ID</th>
                        <th scope="col">NOME</th>
                        <th scope="col">QUANTIDADE</th>
                        <th scope="col">VALOR R$</th>
            
                      </tr>
                    </thead>
                    <tbody>
                      <tr class="text-center">
                        <th scope="row"><img src="{{products.image}}" style="width: 50px;" alt=""></th>
                        <td scope="col">{{products.id}}</td>
                        <td scope="col">{{products.name}}</td>
                        <td scope="col">{{products.amount}}</td>
                        <td scope="col">{{products.value}}</td>
                      
                      </tr>
               
                    </tbody>
                 </table>
                {%if messages %}
                {% for message in messages%} 
                <div class="container container-alert">
                  <div class="row">
                    <div class="col">
                      <div class="alert {{message.tags}}" role="alert">
                          {{message}}  
                      </div>
          
                    </div>
                  </div>
                </div> 
                {% endfor %}
                {% endif %}
              <div class="container container-css">
                <div class="row">
                  <form action="" method="POST" >
                    <div class="col">
                      <h4>Fazer pedido</h4>
                      {{sale.client}}
                      <div class="input-group md-3 p-2">
                          {{sale.amount_buy}}
                          <div class="input-group-append">
                            <button class="btn btn-outline-success" type="submit">Comprar R$</button>
                          </div>
                      </div>
                    </div>
                    {% csrf_token %}
                  </form>
                </div>
              </div>
            </div>
        </div>
    </div>
   
{% endblock content %}

padaria/core/templates/home.html
{% extends "base.html" %}

{% block content %}
  <main role="main">    
    <section class="jumbotron text-center mt-5">
      <div class="container">
        <h1 class="jumbotron-heading">PRODUTOS PARA ENTREGA.</h1>
        <p class="lead text-muted">Receba suas compras sem sair de casa, e tome seu cafe da manhâ com alegria. Venha saboriar umas das nossa guloseimas.</p>
        <p>
        </p>
      </div>
    </section>
    
    <div class="album py-5 bg-light">
      <div class="container">
        <div class="row">

          {% for product in products %}
          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <!-- <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22288%22%20height%3D%22225%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20288%20225%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_18bf4a61cb1%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A14pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_18bf4a61cb1%22%3E%3Crect%20width%3D%22288%22%20height%3D%22225%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2296.84375%22%20y%3D%22118.8%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true"> -->
              <img src="{{product.image}}" style="width:300px" alt="">
              <div class="card-body">
                <p class="card-text">{{product.description}}</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <a href="{{ product.get_absolute_url }}"  class="btn btn-sm btn-outline-primary">Ver detalhe</a>
                    
                  </div>
                  <small class="text-muted col-5">Postado em: {{product.created_at}}</small>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
          
        </div>
      </div>
    </div> 
  </main>
{% endblock content %}

padaria/core/templates/product_list.html
{% extends "base.html" %}

{% block content %}
    <div class="container p-5">
        <div class="row">
            <div class="col">
              <h2 class="text-center">Lista de Produtos</h2>
                <table class="table p-5">
                    <thead>
                      <tr class="text-center">
                        <th scope="col">IMAGEM</th>
                        <th scope="col">ID</th>
                        <th scope="col">NOME</th>
                        <th scope="col">QUANTIDADE</th>
                        <th scope="col">VALOR R$</th>
            
                      </tr>
                    </thead>
                    <tbody>
                    {% for product in products %}
                      <tr class="text-center">
                        <th scope="row"><img src="{{product.image}}" style="width: 50px;" alt=""></th>
                        <td scope="col">{{product.id}}</td>
                        <td scope="col">{{product.name}}</td>
                        <td scope="col">{{product.amount}}</td>
                        <td scope="col">{{product.value}}</td>
                      
                      </tr>
                    {% endfor %}
               
                    </tbody>
                 </table>
            </div>
        </div>
    </div>

{% endblock content %}

padaria/core/templates/register.html
{% extends "base.html" %}
{% block content %}
<div class="container m-3" style="border: 3px solid #0b5ed7;">
    <div class="row m-4">
        <div class="col-6">
            <h3>Cadastro de produtos</h3>
            <form method="POST">
                <div class="row">
                  <div class="row m-2">

                    {{form.image}}
                  </div>
                  <div class="row m-2">
                    {{form.name}}
                  </div>
                  <div class="row m-2">
                    {{form.amount}}
                  </div>

                  <div class="row m-2">
                    {{form.value}}
                  </div>
                  <div class="row m-2">
                    {{form.description}}
                  </div>
                </div>
                <button class="btn btn-secondary" >Limpar</button>
                <button class="btn btn-primary" type="submit">Cadastrar</button>
              </form>

        </div>
        <div class="col-6">
            <img src="https://www.mgpconsultoria.com.br/wp-content/uploads/2018/10/Cadastro-de-Clientes-Imagem4.jpg" style="width:500px; margin-top:180px" alt="">
        </div>
    </div>
</div>
{% endblock content %}

padaria/core/templates/register_client.html
{% extends "base.html" %}
{% block content %}
<div class="container container-css">
    <div class="row">
        <div class="col">    
          <form method="POST">
            {% csrf_token %}
            <div class="row p-3">
                  <h3 class="text-center">Cadastro de Clientes</h3>
                  {%if messages %}
                    {% for message in messages%} 
                    <div class="container container-alert">
                      <div class="row">
                        <div class="col">
                          <div class="alert {{message.tags}}" role="alert">
                            {{message}}  
                          </div>
                        </div>
                      </div>
                    </div> 
                    {% endfor %}
                  {% endif %}
                  <div class="row m-2">
                    {{form.first_name}}
                  </div>
                  <div class="row m-2">
                    {{form.last_name}}
                  </div>
                  <div class="row m-2">
                        {{form.date_of_birth}}
                  </div>
                  <div class="row m-2">
                    {{form.cpf}}
                  </div>
                  <div class="row m-2">
                    {{form.phone_number}}
                  </div>
                  <div class="row m-2">
                    {{form.address}}
                  </div>
                  <button class="btn btn-secondary m-1" onclick="form_client()" >Limpar</button>
                  <button class="btn btn-primary m-1" type="submit">Cadastrar</button>
                </div>
              </form>
        </div>
    </div>
</div>
{% endblock content %}

padaria/core/templates/register_product.html
{% extends "base.html" %}
{% block content %}
<div class="container container-css">
    <div class="row" >
        <div class="col">
          <form method="POST">
            {% csrf_token %}
            <div class="row p-3" >    
              <h3 class="text-center">Cadastro de Produtos</h3>
              {%if messages %}
                    {% for message in messages%} 
                    <div class="container container-alert">
                      <div class="row">
                        <div class="col">
                          <div class="alert {{message.tags}}" role="alert">
                            {{message}}  
                          </div>
                        </div>
                      </div>
                    </div> 
                    {% endfor %}
              {% endif %}
                  <div class="row m-2">
                    {{form.image}}
                  </div>
                  <div class="row m-2">
                    {{form.name}}
                  </div>
                  <div class="row m-2">
                    {{form.amount}}
                  </div>

                  <div class="row m-2">
                    {{form.value}}
                  </div>
                  <div class="row m-2">
                    {{form.description}}
                  </div>
                  <button class="btn btn-secondary m-1" onclick="form_product()">Limpar</button>
                  <button class="btn btn-primary m-1" type="submit">Cadastrar</button>
                </div>
              </form>

        </div>
       
    </div>
</div>
{% endblock content %}

padaria/core/templates/wish_list.html
{% extends "base.html" %}

{% block content %}
    <div class="container p-5">
        <div class="row">
            <div class="col">
              <h2 class="text-center">Lista de Pedidos</h2>
                <table class="table p-5">
                    <thead class="table ">
                      <tr class="text-center ">
                        <th scope="col">CODIGO PRODUTO</th>
                        <th scope="col">CLIENTE</th>
                        <th scope="col">PRODUTO</th>
                        <th scope="col">QUANTIDADE</th>
                        <th scope="col">VALOR UNITÁRIO</th>
                        <th scope="col">TOTAL</th>
                        <th scope="col">DATA</th>

                        
            
                      </tr>
                    </thead>
                    <tbody>
                    {% for sale in sales %}
                      <tr class="text-center">
                        <td scope="col">{{sale.order_number}}</td>
                        <td scope="col">{{sale.client}}</td>
                        <td scope="col">{{sale.product}}</td>
                        <td scope="col">{{sale.amount_buy}}</td>
                        <td scope="col">{{sale.value_sale}}</td>
                        <td scope="col">{{sale.total}}</td>
                        <td scope="col">{{sale.sale_created_at}}</td>
                      
                      </tr>
                    {% endfor %}
               
                    </tbody>
                 </table>
            </div>
        </div>
    </div>

{% endblock content %}